# Generated by Django 3.2.15 on 2022-09-30 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_interface', '0002_controltypes_signaltypes'),
    ]

    operations = [
        migrations.AddField(
            model_name='controltypes',
            name='equipmentId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='admin_interface.equipments'),
            preserve_default=False,
        ),
    ]
