# Generated by Django 3.2.15 on 2022-09-30 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_interface', '0003_controltypes_equipmentid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='controltypes',
            name='sysMedium',
        ),
    ]
