# Generated by Django 3.2.15 on 2022-10-05 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_interface', '0004_remove_controltypes_sysmedium'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='controltypes',
            name='equipmentId',
        ),
        migrations.AddField(
            model_name='controltypes',
            name='sysMedium',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='admin_interface.systemmedium'),
            preserve_default=False,
        ),
    ]
