# Generated by Django 3.2.15 on 2022-10-17 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_interface', '0005_auto_20221005_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='controller',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='equipmentproperty',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='equipmentsection',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='interface',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='platform',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='sysmedium',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='systype',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='sequenceOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('projectId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_interface.project')),
            ],
        ),
    ]
