# Generated by Django 3.2.15 on 2022-10-19 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_interface', '0006_auto_20221017_0930'),
    ]

    operations = [
        migrations.CreateModel(
            name='equipmentProperties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('controlId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_interface.controltypes')),
                ('equipmentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_interface.equipments')),
                ('projectId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_interface.project')),
            ],
        ),
    ]
