# Generated by Django 3.2.15 on 2022-11-04 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_interface', '0007_equipmentproperties'),
    ]

    operations = [
        migrations.CreateModel(
            name='equipmentStages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stageCount', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('equipPropertyId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_interface.equipmentproperties')),
                ('signalType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_interface.signaltypes')),
                ('stageType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_interface.subtypeequipments')),
            ],
        ),
    ]
