# Generated by Django 3.2.15 on 2022-11-07 05:46

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_interface', '0008_equipmentstages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sequenceoperation',
            name='sequence',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
